### ISSUE TITLE
target collection

### ISSUE THREAD

**Issue by AdamSpannbauer** [AdamSpannbauer/game_jam#2]
### attributes
* array of target objects
* order by (takes "color" or "radius" or maybe just arbitrary string that is looked up on the target object to see if it exists to sort by)

### methods
* init should
    * randomly set target locations, colors, radiuses
    * set order by above step and order by user input
    * set order id of each target
* check_hit (just calls target.is_overlap())
* draw (just calls target.draw())

**Comment by JaysonRice** [comment]
Closed by #5
